### PR TITLE
fix: Ensure resultSize resolves to a number.

### LINKED ISSUE #1116: resultSize returns a string
This may be related to the driver, I was using mysql when I came across this, but in my case calling `resultSize` on a query builder is returning a string. Considering the [fallback in the method](https://github.com/Vincit/objection.js/blob/master/lib/queryBuilder/QueryBuilder.js#L525) is to return the number `0`, I think this is a bug. 

To compound the issue for me, the [TS typing](https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts#L849) shows it returns a `Promise<number>`.

If passing the value through `parseInt` would not be considered backwards breaking, I'd be happy to open a PR.

### PR DESCRIPTION
**Pull request by mastermatt**
Fixes #1116.

Passing a number to `parseInt` is safe so this won't break any calling
code that is already manually doing the casting.

### CODE REVIEW

File: tests/unit/queryBuilder/QueryBuilder.js [hunk 1]
```diff
@@ -729,15 +729,16 @@ describe('QueryBuilder', () => {
...
     QueryBuilder.forClass(TestModel)
       .where('test', 100)
       .orderBy('order')
+      .limit(10)
+      .offset(100)
       .resultSize()
       .then(res => {
         expect(executedQueries).to.have.length(1);
         expect(res).to.equal(123);
-        // resultSize should cancel the groupBy call since it doesn't affect the outcome.
```
Comment (mastermatt) [inline tests/unit/queryBuilder/QueryBuilder.js]: Removed this comment because a `GROUP BY` on the underlying query would affect the outcome of a `COUNT`.

Comment (koskimas) [reply tests/unit/queryBuilder/QueryBuilder.js]: Yeah it should have said "orderBy" instead.
